



CREATE TABLE LEAVE( emp_code varchar primary key, month varchar, no_of_days integer );
CREATE TABLE MONTHS( month varchar primary key, days integer );


INSERT INTO MONTHS VALUES('JAN', 31);
INSERT INTO MONTHS VALUES('FEB', 28);
INSERT INTO MONTHS VALUES('MAR', 31);
INSERT INTO MONTHS VALUES('APR', 30);
INSERT INTO MONTHS VALUES('MAY', 31);
INSERT INTO MONTHS VALUES('JUN', 30);
INSERT INTO MONTHS VALUES('JUL', 31);
INSERT INTO MONTHS VALUES('AUG', 31);
INSERT INTO MONTHS VALUES('SEP', 30);
INSERT INTO MONTHS VALUES('OCT', 31);
INSERT INTO MONTHS VALUES('NOV', 30);
INSERT INTO MONTHS VALUES('DEC', 31);


INSERT INTO LEAVE VALUES('SHU' , 'JAN', 5);
INSERT INTO LEAVE VALUES('RAM' , 'JUL', 10);
INSERT INTO LEAVE VALUES('JAN' , 'AUG', 7);
INSERT INTO LEAVE VALUES('ROS' , 'FEB', 9);

