


CREATE TABLE RESULT( ROLL VARCHAR, SCODE VARCHAR, MARKS INTEGER,  CONSTRAINT ROLL_SCODE PRIMARY KEY( ROLL , SCODE ) );
CREATE TABLE BACKPAPER( ROLL VARCHAR , SCODE VARCHAR, CONSTRAINT ROLL_SCODE_1 PRIMARY KEY( ROLL , SCODE ) );


 CREATE OR REPLACE FUNCTION RES_TRIG()
     RETURNS TRIGGER
     LANGUAGE PLPGSQL
 AS $$

 BEGIN
     IF NEW.MARKS > 50 THEN
         DELETE FROM BACKPAPER WHERE BACKPAPER.ROLL = NEW.ROLL;
     ELSE
         INSERT INTO BACKPAPER VALUES(NEW.ROLL, NEW.SCODE);
     END IF;
     RETURN NEW;
 END;
 $$;


CREATE TRIGGER RES_TRIGGER

    AFTER INSERT OR UPDATE ON RESULT

    FOR EACH ROW
        EXECUTE PROCEDURE RES_TRIG();

