


CREATE TABLE REQUEST( REQ_NO INTEGER PRIMARY KEY, REQ_DT DATE );
CREATE TABLE SERVICE_LOG( ENTRY_NO SERIAL PRIMARY KEY, REQ_NO INTEGER, SERVICE_DT DATE);


 CREATE OR REPLACE FUNCTION LOG_TRIG()
     RETURNS TRIGGER
     LANGUAGE PLPGSQL
 AS $$

 BEGIN
     INSERT INTO SERVICE_LOG VALUES(DEFAULT, OLD.REQ_NO, NOW());
     RETURN NEW;
 END;
 $$;


CREATE TRIGGER RES_TRIGGER

    AFTER DELETE ON REQUEST

    FOR EACH ROW
        EXECUTE PROCEDURE LOG_TRIG();

