#!/bin/bash


## concatenation and common substring 

read -p "Enter first string: " str1   
read -p "Enter second string: " str2
str3=$str1$str2
echo "Concatenated : $str3"

# looping over str2
if [[ ${#str2} -gt ${#str1} ]]; then
	temp=$str2
	str2=$str1
	str1=$temp
fi

#stores max sub string len
mx=0
substring=''
for((i=0; i< ${#str2} ;i++)); do
	sub=${str2:$i}
	common=$(echo $str1 | grep -E -o $sub)
	if [[ ${#common} -gt $mx ]]; then
		substring=$common
		mx=${#common}		
	fi
done


echo "Common substring of $str1 and $str2 is $substring"






