#!/bin/bash
dir=$1
fc=0 #file count
declare -a file_2018=()

check_dir(){
    if [[ -d $1 ]]; then
        return 0
    fi
    return 1
}

rec(){
    #echo "DIRECTORY : $1"
    OIFS="$IFS"
    IFS=$'\n'
    for file in $(ls $1); do
        if [[ -f $file ]]; then
            #echo " - $file"
            fc=$((fc +1))
            # storing in an array
            temp=($( stat -f "%Sm" $file | tr ' ' $'\n' ))
            # bash is 1 indexed
            # bash array is 0 indexed
            # echo ${temp[3]}
            if [[ ${temp[3]} -gt 2018 ]] && [[ ${temp[3]} -lt 2020 ]]; then
                file_2018+=($file)
            fi
        else
            rec "$1/$file"
        fi
    done
    IFS="$OIFS"
}




rec $1
echo "Total files $fc"

echo "All files created in year 2018"

for file in "${file_2018[@]}"; do
    echo "$file"
done



